local: &local
 adapter: postgresql
 username: postgres
 password:
 host: localhost
development:
 <<: *local
 database: todo_app_dev
test:
 <<: *local
 database: todo_app_test
production:
 <<: *local
 database: todo_app_production

 sqlite: &sqlite
   adapter: sqlite3
   database: db/<%= Rails.env %>.sqlite3

 mysql: &mysql
   adapter: mysql2
   username: root
   password:
   database: myapp_<%= Rails.env %>

 postgresql: &postgresql
   adapter: postgresql
   username: postgres
   password:
   database: myapp_<%= Rails.env %>
   min_messages: ERROR

 defaults: &defaults
   pool: 5
   timeout: 5000
   host: localhost
   <<: *<%= ENV['DB'] || "postgresql" %>

 development:
   <<: *defaults

 test:
   <<: *defaults

 production:
   <<: *defaults
   # TODO: Add erb-echo of credentials