local: &local
 adapter: postgresql
 username: postgres
 password:
 host: localhost
development:
 <<: *local
 database: todo_app_dev
test:
 <<: *local
 database: todo_app_test
production:
 <<: *local
 database: todo_app_production